### ISSUE TITLE
although I passed all 3 test,  "learn submit" is not working and won't let me submit my finished work to proceed

### ISSUE THREAD

**Issue by cesarmota123** [learn-co-curriculum/ruby-enumerables-reverse-each-word-lab#1]
I have obviously and successfully passed all 3 test .
when I hit learn submit the green button on the right side will not load .
I am unable to move past this lesson even though I have successfully finished the lab.

**Comment by rrcobb** [comment]
Hi there! This request sounds like an improvement to or a problem with the Learn platform.

Our product team can help you with this. You can reach them at support@learn.co.

[Raising issues on GitHub][raise], like you've done here should happen when
there are problems with the curriculum itself (doesn't work, throws a Ruby
error, etc.)

If, on the other hand, we've misunderstood the purpose of this request, please
re-open this issue, provide any additional information you can to clarify our error,
and we will try to find a fix.

[raise]: http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson
